# Generated by Django 5.1.3 on 2024-11-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ne", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("gsm", models.BooleanField(default=False)),
                ("umts", models.BooleanField(default=False)),
                ("lte", models.BooleanField(default=False)),
                ("status", models.CharField(max_length=50)),
            ],
        ),
    ]
